import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsDateString,
  IsEnum,
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsPositive,
  IsString,
  MaxLength,
  Min,
  ValidateIf,
} from 'class-validator';
import { MovementType } from '@prisma/client';
import { PaginationDto } from '../../common/dto/pagination.dto';

// Transfers, picking outputs and returns are generated by their own flows.
export const MANUAL_MOVEMENT_TYPES = [
  'opening_balance',
  'purchase_receipt',
  'adjustment_increase',
  'adjustment_decrease',
] as const satisfies readonly MovementType[];

export type ManualMovementType = (typeof MANUAL_MOVEMENT_TYPES)[number];

export class CreateMovementDto {
  @ApiProperty({ enum: MANUAL_MOVEMENT_TYPES })
  @IsEnum(MANUAL_MOVEMENT_TYPES)
  type!: ManualMovementType;

  @ApiProperty({ minimum: 1 })
  @IsInt()
  @IsPositive()
  quantity!: number;

  @ApiPropertyOptional({ description: "Defaults to the user's warehouse" })
  @IsOptional()
  @IsString()
  @IsNotEmpty()
  warehouseId?: string;

  @ApiPropertyOptional({
    description: 'Location that receives (increases) or gives (decreases) the units; decreases without it take from locations in pick sequence',
  })
  @IsOptional()
  @IsString()
  locationId?: string;

  @ApiPropertyOptional({ maxLength: 500 })
  @IsOptional()
  @IsString()
  @MaxLength(500)
  notes?: string;
}

export class TransferDto {
  @ApiProperty() @IsString() @IsNotEmpty() productId!: string;
  @ApiProperty() @IsString() @IsNotEmpty() fromWarehouseId!: string;
  @ApiProperty() @IsString() @IsNotEmpty() toWarehouseId!: string;
  @ApiProperty({ minimum: 1 }) @IsInt() @IsPositive() quantity!: number;
  @ApiPropertyOptional({ maxLength: 500 }) @IsOptional() @IsString() @MaxLength(500) notes?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() fromLocationId?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() toLocationId?: string;
}

export class RelocateDto {
  @ApiProperty() @IsString() @IsNotEmpty() productId!: string;
  @ApiProperty() @IsString() @IsNotEmpty() warehouseId!: string;
  @ApiPropertyOptional({ description: 'Omit to take stock not assigned to any location' })
  @IsOptional()
  @IsString()
  fromLocationId?: string;

  @ApiPropertyOptional({ description: 'Omit to leave the units without a location' })
  @IsOptional()
  @IsString()
  toLocationId?: string;

  @ApiProperty({ minimum: 1 }) @IsInt() @IsPositive() quantity!: number;
  @ApiPropertyOptional({ maxLength: 500 }) @IsOptional() @IsString() @MaxLength(500) notes?: string;
}

export class LocationStockQueryDto extends PaginationDto {
  @ApiProperty() @IsString() @IsNotEmpty() warehouseId!: string;
  @ApiPropertyOptional() @IsOptional() @IsString() productId?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() locationId?: string;
}

export class UpdateStockSettingsDto {
  @ApiPropertyOptional({ nullable: true, maxLength: 50, example: 'A-01-03' })
  @IsOptional()
  @ValidateIf((_, v) => v !== null)
  @IsString()
  @MaxLength(50)
  location?: string | null;

  @ApiPropertyOptional({ minimum: 0, example: 10 })
  @IsOptional()
  @IsInt()
  @Min(0)
  minStock?: number;
}

export class MovementsQueryDto extends PaginationDto {
  @ApiPropertyOptional({ description: "Defaults to the user's warehouse; admins see all when omitted" })
  @IsOptional()
  @IsString()
  warehouseId?: string;

  @ApiPropertyOptional({ enum: MovementType })
  @IsOptional()
  @IsEnum(MovementType)
  type?: MovementType;

  @ApiPropertyOptional({ example: '2025-01-01' })
  @IsOptional()
  @IsDateString()
  dateFrom?: string;

  @ApiPropertyOptional({ example: '2025-12-31' })
  @IsOptional()
  @IsDateString()
  dateTo?: string;
}
