export interface ObjectStorage {
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
  publicUrl(key: string): string;
  /** Inverse of publicUrl; null when the URL does not point to this storage. */
  keyFromUrl(url: string): string | null;
}

export const OBJECT_STORAGE = Symbol('OBJECT_STORAGE');

// Files that must not be publicly reachable (uploaded imports, error reports).
export const PRIVATE_STORAGE = Symbol('PRIVATE_STORAGE');

// Keys are generated by the API, but they are still validated before touching disk or the bucket.
const SAFE_KEY = /^[a-zA-Z0-9][a-zA-Z0-9/_.-]*$/;

export function isSafeKey(key: string): boolean {
  return SAFE_KEY.test(key) && !key.split('/').some((segment) => segment === '' || segment === '.' || segment === '..');
}

const URL_ORIGIN = /^[a-z][a-z0-9+.-]*:\/\/[^/]+/i;

export function keyFromPublicUrl(url: string, baseUrl: string): string | null {
  const base = baseUrl.replace(/\/+$/, '') + '/';
  const path = url.split(/[?#]/)[0];
  // A root-relative base also recognizes absolute URLs stored before uploads stopped including the host.
  const clean = base.startsWith('/') ? path.replace(URL_ORIGIN, '') : path;
  if (!clean.startsWith(base)) return null;
  const key = decodeURIComponent(clean.slice(base.length));
  return isSafeKey(key) ? key : null;
}
