export interface ObjectStorage {
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  delete(key: string): Promise<void>;
  publicUrl(key: string): string;
  /** Inverse of publicUrl; null when the URL does not point to this storage. */
  keyFromUrl(url: string): string | null;
}

export const OBJECT_STORAGE = Symbol('OBJECT_STORAGE');

// Keys are generated by the API, but they are still validated before touching disk or the bucket.
const SAFE_KEY = /^[a-zA-Z0-9][a-zA-Z0-9/_.-]*$/;

export function isSafeKey(key: string): boolean {
  return SAFE_KEY.test(key) && !key.split('/').some((segment) => segment === '' || segment === '.' || segment === '..');
}

export function keyFromPublicUrl(url: string, baseUrl: string): string | null {
  const base = baseUrl.replace(/\/+$/, '') + '/';
  const clean = url.split(/[?#]/)[0];
  if (!clean.startsWith(base)) return null;
  const key = decodeURIComponent(clean.slice(base.length));
  return isSafeKey(key) ? key : null;
}
